name: Testes JUnit - PI Etapa 7

on:
  push:
    branches:
      - main
      - etapa7-junit
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v7

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Executar testes unitários
        run: mvn --batch-mode clean test
